spring.application.name=ims
spring.datasource.url=jdbc:postgresql://localhost:5432/ECom_db
spring.datasource.username=postgres
spring.datasource.password=qwerty05.#Ab
spring.jpa.hibernate.ddl-auto=update